### ISSUE TITLE
error nggonmu

### ISSUE THREAD

**Issue by whdhdyt21** [Raturu0/quotes-lucu#2]
hello world mu nggowo bahasa inggris

**Comment by whdhdyt21** [comment]
harus e nggowo bahasa indonesia

**Comment by Raturu0** [comment]
> harus e nggowo bahasa indonesia

ngantuk aku

**Comment by Raturu0** [comment]
> harus e nggowo bahasa indones

aksen jowo

**Comment by whdhdyt21** [comment]
wkwk wokeh berhasil 😂

**Comment by Raturu0** [comment]
> wkwk wokeh berhasil 😂

op y wkw

**Comment by Raturu0** [comment]
tes komen berhasil opo ra hid?

**Comment by Raturu0** [comment]
oalaah kene to komene

**Comment by whdhdyt21** [comment]
isoh Ziz, keterangan e koe reopen diskusi

**Comment by Raturu0** [comment]
oalah ok hid wkw

**Comment by Raturu0** [comment]
close e ng ndi hid

**Comment by Raturu0** [comment]
tes

**Comment by Raturu0** [comment]
close?

**Comment by Raturu0** [comment]
tak tutup ki

**Comment by whdhdyt21** [comment]
close isue nggon repositoriku

**Comment by whdhdyt21** [comment]
udu kene
